SHOW PDBS;

-- Connect to the PDB
ALTER SESSION SET CONTAINER = XEPDB1;

-- Create user inside PDB
CREATE USER budget_as_you_go IDENTIFIED BY budget123;
GRANT CONNECT, RESOURCE TO budget_as_you_go;
ALTER USER budget_as_you_go QUOTA UNLIMITED ON USERS;




-- Switch to the new schema
ALTER SESSION SET CURRENT_SCHEMA = budget_as_you_go;

-- Users Table
CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    password VARCHAR2(100) NOT NULL
);

-- Categories Table
CREATE TABLE categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL
);

-- Expenses Table
CREATE TABLE expenses (
    expense_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    description VARCHAR2(255),
    amount NUMBER NOT NULL,
    expense_date DATE NOT NULL,
    photo_path VARCHAR2(255),
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Goals Table
CREATE TABLE goals (
    goal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    min_goal NUMBER,
    max_goal NUMBER,
    month VARCHAR2(50),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

-- Profiles Table
CREATE TABLE profiles (
    profile_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    profile_picture VARCHAR2(255),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);









